name: Deploy mdBook

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Устанавливаем mdBook
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: "latest"

      # Устанавливаем Rust
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      # Кэш Cargo для ускорения сборок
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: "."

      # Клонируем mdbook-drawio вручную с токеном
      - name: Clone mdbook-drawio
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git clone https://x-access-token:${GITHUB_TOKEN}@github.com/drogue-iot/mdbook-drawio.git
          cd mdbook-drawio
          cargo build --release
          sudo cp target/release/mdbook-drawio /usr/local/bin/

      # Сборка mdBook
      - name: Build Book
        run: mdbook build

      # Деплой на GitHub Pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
